version: "3.9"
services:
  audit:
    image: audit:0.0.1
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
      - SPRING_RABBITMQ_PORT=5672
    ports:
      - "8082:8080"
    depends_on:
      - rabbit
  business:
    image: business:0.0.1
    environment:
      - SPRING_RABBITMQ_HOST=rabbit
      - SPRING_RABBITMQ_PORT=5672
    ports:
      - "8081:8080"
    depends_on:
      - rabbit
  rabbit:
    image: rabbitmq:3.9.5
    ports:
      - "5672:5672"
      - "15672:15672"